<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<title>ROBINSUN Control Panel</title>
	<link href="/mchp.css" rel="stylesheet" type="text/css" />
	<script src="../js/mchp.js" type="text/javascript"></script>
	<script src="../js/smoothie.js" type="text/javascript"></script>
</head>

<body>
<center>
<div id="shadow-one"><div id="shadow-two"><div id="shadow-three"><div id="shadow-four">
<div id="page">
	
	<div id="logo"> <a href="/index.htm"> <img style="width=50; height=10;" src="../images/robinsun.png" alt="ROBINSUN"/> </a> </div>
	<h2> Available modes: </h2>
	<ul id="menu">
		<li><a href="/charts.htm">Live Charts</a></li>
		<li><a href="/autocontroller.htm">Controller Parameters</a></li>
		<li><a href="/manualcontroller.htm">Manual Controller</a></li>
		<li><a href="http://www.robinsun.eu" target="_blank">Team Website</a></li>
	</ul>
	
